-- Migration: Create WS_MQTT_TOPICS table for admin-managed MQTT subscriptions
-- Description: Stores configurable topic filters subscribed by the MQTT bridge
-- Compatible with Oracle 11g

-- Sequence for primary key
CREATE SEQUENCE WS_MQTT_TOPICS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Table
CREATE TABLE WS_MQTT_TOPICS (
  TOPIC_ID      NUMBER PRIMARY KEY,
  TOPIC_FILTER  VARCHAR2(500) NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR2(500),
  IS_ACTIVE     NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
  CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Auto-increment trigger
CREATE OR REPLACE TRIGGER WS_MQTT_TOPICS_TRG
BEFORE INSERT ON WS_MQTT_TOPICS
FOR EACH ROW
BEGIN
  IF :NEW.TOPIC_ID IS NULL THEN
    SELECT WS_MQTT_TOPICS_SEQ.NEXTVAL INTO :NEW.TOPIC_ID FROM DUAL;
  END IF;
END;

-- Index on active topics
CREATE INDEX IDX_WS_MQTT_TOPICS_ACTIVE ON WS_MQTT_TOPICS(IS_ACTIVE);

-- Seed initial topic filters (based on G14 gateclientmqtt publishers)
INSERT INTO WS_MQTT_TOPICS (TOPIC_FILTER, DESCRIPTION) VALUES ('/monitoring/gate',       'Pre-gate sensor');
INSERT INTO WS_MQTT_TOPICS (TOPIC_FILTER, DESCRIPTION) VALUES ('/monitoring/buffer',     'Buffer system');
INSERT INTO WS_MQTT_TOPICS (TOPIC_FILTER, DESCRIPTION) VALUES ('/monitoring/gatemain',   'Main gate');
INSERT INTO WS_MQTT_TOPICS (TOPIC_FILTER, DESCRIPTION) VALUES ('/monitoring/ocr',        'OCR system');
INSERT INTO WS_MQTT_TOPICS (TOPIC_FILTER, DESCRIPTION) VALUES ('/monitoring/gatedevice', 'Gate device');

COMMIT;

-- Verification
SELECT TOPIC_ID, TOPIC_FILTER, IS_ACTIVE FROM WS_MQTT_TOPICS ORDER BY TOPIC_ID;
